from pydantic import BaseModel, Field
from typing import List, Dict, Any, Optional

class ResearchProposal(BaseModel):
    """
    Schema for Research Proposals generated by the Reasoning Specialist.
    Matches research/loop/prompts/proposal.md.
    """
    experiment_id: str = Field(..., description="Unique ID for this experiment, e.g. EXP_20240217_1000")
    priority: str = Field(..., description="Priority: HIGH, MED, or LOW")
    hypothesis: str = Field(..., description="Data-driven hypothesis for this experiment")
    strategy: str = Field(..., description="Strategy name from registry.json")
    symbol: str = Field(..., description="Target symbol from registry.json")
    timeframe: str = Field(..., description="Timeframe from registry.json")
    parameters: Dict[str, Any] = Field(..., description="Hyperparameters for the strategy")
    metrics_to_watch: List[str] = Field(default_factory=list, description="KPis to focus on during backtest")
    reasoning: str = Field(..., description="Detailed reasoning for why this experiment was proposed")

    def validate_registry(self, registry: Dict[str, Any]) -> bool:
        """
        Validate this proposal against the registry.json allowlist.
        Returns True if valid, raises ValueError if not.
        """
        if self.strategy not in registry.get("allowed_strategies", []):
            raise ValueError(f"Strategy {self.strategy} not in allowlist")
        
        if self.symbol not in registry.get("allowed_symbols", []):
            raise ValueError(f"Symbol {self.symbol} not in allowlist")
            
        if self.timeframe not in registry.get("allowed_timeframes", []):
            raise ValueError(f"Timeframe {self.timeframe} not in allowlist")
            
        # Parameter range check
        ranges = registry.get("parameter_ranges", {})
        for key, value in self.parameters.items():
            if key in ranges:
                low, high = ranges[key]
                if not (low <= value <= high):
                    raise ValueError(f"Parameter {key}={value} out of range [{low}, {high}]")
        
        # Forbidden keywords check
        forbidden = registry.get("forbidden_keywords", [])
        for word in forbidden:
            if word.lower() in self.reasoning.lower() or word.lower() in self.hypothesis.lower():
                raise ValueError(f"Forbidden keyword '{word}' found in proposal")
                
        return True
