#!/usr/bin/env bash
set -euo pipefail

usage() {
  cat <<'EOF'
Usage:
  bash scripts/auto_pr.sh [options]

Options:
  --generator "<cmd>"      Run optional generator command (repeatable)
  --title "<title>"        Override PR title
  --body "<body>"          Override PR body
  --branch-prefix "<name>" Branch prefix (default: codex/auto-pr)
  --base "<ref>"           PR base branch (default: main)
  --dry-run                Validate and print plan without creating PR
  -h, --help               Show this help

Behavior:
  1) Requires clean worktree
  2) Syncs main from origin
  3) Creates a fresh codex/* branch
  4) Runs optional generators
  5) Allows changes only under docs/** and ops/**/*.md
  6) If no changes: exits 0
  7) Commits, pushes, opens PR, waits checks, squash-merges, syncs main
EOF
}

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$REPO_ROOT"

BRANCH_PREFIX="codex/auto-pr"
BASE_BRANCH="main"
CUSTOM_TITLE=""
CUSTOM_BODY=""
DRY_RUN=0
GENERATORS=()

while [[ $# -gt 0 ]]; do
  case "$1" in
    --generator)
      if [[ $# -lt 2 ]]; then
        echo "ERROR: --generator requires a command string" >&2
        exit 2
      fi
      GENERATORS+=("$2")
      shift 2
      ;;
    --title)
      if [[ $# -lt 2 ]]; then
        echo "ERROR: --title requires a value" >&2
        exit 2
      fi
      CUSTOM_TITLE="$2"
      shift 2
      ;;
    --body)
      if [[ $# -lt 2 ]]; then
        echo "ERROR: --body requires a value" >&2
        exit 2
      fi
      CUSTOM_BODY="$2"
      shift 2
      ;;
    --branch-prefix)
      if [[ $# -lt 2 ]]; then
        echo "ERROR: --branch-prefix requires a value" >&2
        exit 2
      fi
      BRANCH_PREFIX="$2"
      shift 2
      ;;
    --base)
      if [[ $# -lt 2 ]]; then
        echo "ERROR: --base requires a value" >&2
        exit 2
      fi
      BASE_BRANCH="$2"
      shift 2
      ;;
    --dry-run)
      DRY_RUN=1
      shift
      ;;
    -h|--help)
      usage
      exit 0
      ;;
    *)
      echo "ERROR: unknown argument: $1" >&2
      usage
      exit 2
      ;;
  esac
done

require_cmd() {
  local cmd="$1"
  if ! command -v "$cmd" >/dev/null 2>&1; then
    echo "ERROR: required command not found: $cmd" >&2
    exit 3
  fi
}

require_cmd git
require_cmd gh
require_cmd bash
require_cmd rg

if ! gh auth status >/dev/null 2>&1; then
  echo "ERROR: gh auth is not ready. Run: gh auth login" >&2
  exit 4
fi

if [[ -n "$(git status --porcelain)" ]]; then
  echo "ERROR: worktree is dirty. Please commit/stash first." >&2
  git status --short >&2
  exit 5
fi

git fetch origin
git checkout "$BASE_BRANCH"
git pull --ff-only origin "$BASE_BRANCH"

TS_UTC="$(date -u +%Y%m%d_%H%M%S)"
BRANCH_NAME="${BRANCH_PREFIX}-${TS_UTC}"
git checkout -b "$BRANCH_NAME"

for gen_cmd in "${GENERATORS[@]}"; do
  echo "[auto_pr] running generator: $gen_cmd"
  bash -lc "$gen_cmd"
done

# Hard red-line: never stage data/**
if git diff --cached --name-only | rg '^data/' >/dev/null 2>&1; then
  echo "ERROR: detected staged data/** changes. Aborting." >&2
  exit 6
fi

if ! bash scripts/check_allowlist_changes.sh; then
  echo "ERROR: non-allowlisted file changes detected. Aborting." >&2
  exit 7
fi

CHANGED_FILES=()
while IFS= read -r line; do
  [[ -z "$line" ]] && continue
  CHANGED_FILES+=("$line")
done < <(bash scripts/check_allowlist_changes.sh --list-changed)
if [[ ${#CHANGED_FILES[@]} -eq 0 ]]; then
  echo "[auto_pr] no allowlisted changes detected; nothing to PR."
  git checkout "$BASE_BRANCH"
  git branch -D "$BRANCH_NAME" >/dev/null 2>&1 || true
  exit 0
fi

classify_change_type() {
  local has_docs=0
  local has_skills_docs=0
  local has_audit_docs=0
  local has_ops_md=0
  local p=""
  for p in "${CHANGED_FILES[@]}"; do
    [[ "$p" == docs/* ]] && has_docs=1
    [[ "$p" == docs/skills/* ]] && has_skills_docs=1
    [[ "$p" == docs/audits/* ]] && has_audit_docs=1
    [[ "$p" =~ ^ops/.+\.md$ ]] && has_ops_md=1
  done
  if [[ "$has_audit_docs" -eq 1 ]]; then
    echo "ops-audit"
    return
  fi
  if [[ "$has_skills_docs" -eq 1 ]]; then
    echo "skills-docs"
    return
  fi
  if [[ "$has_docs" -eq 1 && "$has_ops_md" -eq 0 ]]; then
    echo "docs-only"
    return
  fi
  echo "docs-meta"
}

CHANGE_CLASS="$(classify_change_type)"
DEFAULT_TITLE="chore(auto-pr): ${CHANGE_CLASS} update (${TS_UTC})"
TITLE="${CUSTOM_TITLE:-$DEFAULT_TITLE}"

BODY_FILE="$(mktemp /tmp/hongstr_auto_pr_body.XXXXXX.md)"
{
  if [[ -n "$CUSTOM_BODY" ]]; then
    echo "$CUSTOM_BODY"
    echo
  else
    echo "Automated PR generated by \`scripts/auto_pr.sh\`."
    echo
    echo "Change class: \`${CHANGE_CLASS}\`"
    echo
    echo "Changed files:"
    for p in "${CHANGED_FILES[@]}"; do
      echo "- \`$p\`"
    done
    echo
  fi
  echo "Safety Statement:"
  echo "- No \`src/hongstr/**\` modifications."
  echo "- No \`data/**\` artifacts committed."
  echo "- report_only defaults preserved."
  echo "- tg_cp no-exec guardrails preserved."
  echo
  echo "Rollback:"
  echo "- \`git revert <merge_commit_sha>\`"
} >"$BODY_FILE"

if [[ "$DRY_RUN" -eq 1 ]]; then
  echo "[auto_pr] dry-run complete."
  echo "  branch: $BRANCH_NAME"
  echo "  title : $TITLE"
  echo "  class : $CHANGE_CLASS"
  echo "  files :"
  for p in "${CHANGED_FILES[@]}"; do
    echo "    - $p"
  done
  rm -f "$BODY_FILE"
  exit 0
fi

git add -- "${CHANGED_FILES[@]}"

if git diff --cached --name-only | rg '^data/' >/dev/null 2>&1; then
  echo "ERROR: refusing to commit data/**" >&2
  exit 8
fi

COMMIT_MSG="chore(auto-pr): ${CHANGE_CLASS} update"
git commit -m "$COMMIT_MSG"
git push -u origin "$BRANCH_NAME"

PR_URL="$(gh pr create --base "$BASE_BRANCH" --head "$BRANCH_NAME" --title "$TITLE" --body-file "$BODY_FILE")"
echo "[auto_pr] created PR: $PR_URL"

echo "[auto_pr] waiting for checks..."
gh pr checks "$PR_URL" --watch --interval 10

echo "[auto_pr] checks passed; squash merging..."
gh pr merge "$PR_URL" --squash --delete-branch

git checkout "$BASE_BRANCH"
git pull --ff-only origin "$BASE_BRANCH"
git branch -D "$BRANCH_NAME" >/dev/null 2>&1 || true

rm -f "$BODY_FILE"
echo "[auto_pr] done."
